# .streamlit/secrets.toml
[connections.gsheets]
spreadsheet  = "https://docs.google.com/spreadsheets/d/16pVbDPxIoGL0psJYCDzmRKK5-QMkVH5qp2gA8w9r1kw/edit?pli=1&gid=1101470363#gid=1101470363"

[connections.snowflake]
account = ""
user = ""
password  = ""
role = "ACCOUNTADMIN"
warehouse = "COMPUTE_WH"
database = "PETS"
schema = "PUBLIC"

[mongo]
uri = ""
db_name = "test_db"